# -*- coding: utf-8 -*-
"""EDA_AND_DATA_VISUALIZATION_PROJECT_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z5Yu7r8LXzy0F4Fa6zIEWgUve4v-x9Cc
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files

# 1. Load the cleaned dataset
df_clean = pd.read_csv('/content/ecommerce_data_clean.csv')

# 2. Ensure transaction_date is parsed as datetime
df_clean['transaction_date'] = pd.to_datetime(df_clean['transaction_date'])

# 3. Quick structural verification
print("Dataset Shape:", df_clean.shape)
print("\nData Types:")
print(df_clean.dtypes)
df_clean.head()

"""Step 2: Calculate High-Level Business KPIs & Statistics"""

# 1. Calculate Core KPI Metrics
total_revenue = df_clean['total_spent'].sum()
total_transactions = len(df_clean)
unique_customers = df_clean['customer_id'].nunique()
aov = df_clean['total_spent'].mean()
median_ov = df_clean['total_spent'].median()
avg_items_per_order = df_clean['quantity'].mean()

# 2. Build KPI Summary DataFrame
kpi_summary = pd.DataFrame({
    'Metric': [
        'Total Revenue ($)',
        'Total Transactions',
        'Unique Customers',
        'Average Order Value ($)',
        'Median Order Value ($)',
        'Average Quantity per Order'
    ],
    'Value': [
        round(total_revenue, 2),
        total_transactions,
        unique_customers,
        round(aov, 2),
        round(median_ov, 2),
        round(avg_items_per_order, 2)
    ]
})

# 3. Descriptive Statistics for Numeric Columns
spend_stats = df_clean[['quantity', 'price_per_unit', 'total_spent']].describe().T

print("=== OVERALL BUSINESS KPIs ===")
print(kpi_summary.to_string(index=False))
print("\n=== DESCRIPTIVE STATISTICS ===")
print(spend_stats)

"""Step 3: Export KPI Data to CSV & Download"""

# Save tables locally in Colab workspace
kpi_summary.to_csv('client_kpi_summary.csv', index=False)
spend_stats.to_csv('client_descriptive_stats.csv')

# Download CSVs directly to your computer
files.download('client_kpi_summary.csv')
files.download('client_descriptive_stats.csv')
print("CSV deliverables saved and download initiated!")

"""Step 4: Generate, Save & Download Spend Distribution Visualization"""

# Set professional styling
sns.set_theme(style="whitegrid")
plt.figure(figsize=(10, 5))

# Plot total_spent distribution
sns.histplot(df_clean['total_spent'], kde=True, color='#1f77b4', bins=30)
plt.axvline(aov, color='red', linestyle='--', linewidth=2, label=f'AOV (${aov:,.2f})')
plt.axvline(median_ov, color='green', linestyle='-', linewidth=2, label=f'Median (${median_ov:,.2f})')

plt.title('Transaction Value Distribution (Total Spent)', fontsize=14, fontweight='bold', pad=15)
plt.xlabel('Total Spent ($)', fontsize=12)
plt.ylabel('Transaction Count', fontsize=12)
plt.legend(fontsize=11)
plt.tight_layout()

plt.show()

# Save plot as high-resolution PNG (300 DPI)
image_filename = 'chart_1_transaction_value_distribution.png'
plt.savefig(image_filename, dpi=300, bbox_inches='tight')

# Trigger direct browser download
files.download(image_filename)

print("Chart image saved and download initiated!")

"""Phase 2: Product & Category Performance Analysis!"""

#Step 1: Calculate Category Performance Metrics

# Group data by category
category_perf = df_clean.groupby('category').agg(
    total_revenue=('total_spent', 'sum'),
    transaction_count=('total_spent', 'count'),
    avg_price_per_unit=('price_per_unit', 'mean'),
    average_order_value=('total_spent', 'mean')
).reset_index()

# Sort by highest total revenue first
category_perf = category_perf.sort_values(by='total_revenue', ascending=False)

# Round numbers to 2 decimal places for easy reading
category_perf = category_perf.round(2)

# Print the result
print("=== CATEGORY PERFORMANCE ANALYSIS ===")
print(category_perf)

# Save category analysis to CSV file
category_perf.to_csv('client_category_performance.csv', index=False)

# Download CSV file to your computer
files.download('client_category_performance.csv')

print("Category performance CSV saved and download initiated!")

# Set picture size
plt.figure(figsize=(10, 6))

# Make a bar chart of total revenue by category
sns.barplot(
    data=category_perf,
    x='total_revenue',
    y='category',
    palette='Blues_r'
)

# Add titles and labels
plt.title('Total Revenue by Product Category', fontsize=14, fontweight='bold')
plt.xlabel('Total Revenue ($)', fontsize=12)
plt.ylabel('Category', fontsize=12)

# Make layout neat
plt.tight_layout()

# Show the chart
plt.show()

# Save chart image
image_filename = 'chart_2_total_revenue_by_category.png'
plt.savefig(image_filename, dpi=300, bbox_inches='tight')

# Download image file
files.download(image_filename)

print("Chart image saved and download initiated!")

"""Phase 3: Payment Method & Customer Order Analysis."""

# Group data by payment method
payment_perf = df_clean.groupby('payment_method').agg(
    total_revenue=('total_spent', 'sum'),
    transaction_count=('total_spent', 'count'),
    average_order_value=('total_spent', 'mean')
).reset_index()

# Sort by highest total revenue first
payment_perf = payment_perf.sort_values(by='total_revenue', ascending=False)

# Round numbers to 2 decimal places for easy reading
payment_perf = payment_perf.round(2)

# Print the result
print("=== PAYMENT METHOD PERFORMANCE ===")
print(payment_perf)

# Save payment performance to CSV file
payment_perf.to_csv('client_payment_performance.csv', index=False)

# Download CSV file to your computer
files.download('client_payment_performance.csv')

print("Payment performance CSV saved and download initiated!")

# Set figure size
plt.figure(figsize=(8, 5))

# Create bar plot for total revenue by payment method
sns.barplot(
    data=payment_perf,
    x='payment_method',
    y='total_revenue',
    palette='Set2'
)

# Add title and labels
plt.title('Total Revenue by Payment Method', fontsize=14, fontweight='bold')
plt.xlabel('Payment Method', fontsize=12)
plt.ylabel('Total Revenue ($)', fontsize=12)

# Adjust layout neatly
plt.tight_layout()

# Display the plot
plt.show()

# Save chart image
image_filename = 'chart_3_total_revenue_by_payment_method.png'
plt.savefig(image_filename, dpi=300, bbox_inches='tight')

# Download image file
files.download(image_filename)

print("Chart image saved and download initiated!")

"""Phase 4: Time-Series / Monthly Revenue Trends."""

# Phase 4 — Step 1: Calculate Monthly Revenue & Order Volume

# 1. Create a Year-Month column for grouping
df_clean['year_month'] = df_clean['transaction_date'].dt.to_period('M')

# 2. Group data by year_month
monthly_perf = df_clean.groupby('year_month').agg(
    total_revenue=('total_spent', 'sum'),
    transaction_count=('total_spent', 'count'),
    average_order_value=('total_spent', 'mean')
).reset_index()

# 3. Convert year_month to string so it displays nicely
monthly_perf['year_month'] = monthly_perf['year_month'].astype(str)

# 4. Round values to 2 decimal places
monthly_perf = monthly_perf.round(2)

# Print monthly performance summary
print("=== MONTHLY REVENUE & ORDER TRENDS ===")
print(monthly_perf)

# Save monthly performance to CSV file
monthly_perf.to_csv('client_monthly_performance.csv', index=False)

# Download CSV file to your computer
files.download('client_monthly_performance.csv')

print("Monthly performance CSV saved and download initiated!")

# Set picture size
plt.figure(figsize=(14, 6))

# Make a line plot for monthly revenue
sns.lineplot(
    data=monthly_perf,
    x='year_month',
    y='total_revenue',
    marker='o',
    color='#1f77b4',
    linewidth=2.5
)

# Add titles and axis labels
plt.title('Monthly Revenue Trend (Jan 2022 - Jan 2025)', fontsize=14, fontweight='bold')
plt.xlabel('Year-Month', fontsize=12)
plt.ylabel('Total Revenue ($)', fontsize=12)

# Rotate month labels on the X-axis so they are easy to read
plt.xticks(rotation=45)

# Make layout clean
plt.tight_layout()

# Display the chart
plt.show()

# Save chart image
image_filename = 'chart_4_monthly_revenue_trend.png'
plt.savefig(image_filename, dpi=300, bbox_inches='tight')

# Download image file
files.download(image_filename)

print("Chart image saved and download initiated!")