# -*- coding: utf-8 -*-
"""python_proj1-data_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tTFGbzwN6_v39_09_iQGIGFxohhTdvQy
"""

import pandas as pd
import numpy as np

df=pd.read_csv('/content/retail_store_sales.csv')

df.head()

df.info()

#make coloumns name in lower caseand replace  spaces with _
df.columns= df.columns.str.lower().str.replace(' ','_')

df.columns

#check duplicate rows
df.duplicated().sum()

#as duplicate rowsare 0, check duplicated id's
df['transaction_id'].duplicated().sum()

#as no duplicated id found, check null rows
df.isnull().sum()

#count unique falues including NAN
df['discount_applied'].value_counts(dropna=False)

# FILL ANY MISSING OR nan VALUE with false and change data type of column to boolean
df['discount_applied']=df['discount_applied'].fillna(False).astype('bool')

#It counts the occurrences of each value in discount_applied (including nulls if any remain)
df['discount_applied'].value_counts(dropna=False)

#total_spent=price_per_unit*quantity
#We can fill missing values in any one of these columns if the other two are present.
df[df['price_per_unit'].isnull()& df['quantity'].notnull()& df['total_spent'].notnull()].shape[0]

#That means all 609 missing price_per_unit values
#can be perfectly calculated using the formula

# Calculate and fill missing price_per_unit
df['price_per_unit'] = df['price_per_unit'].fillna(df['total_spent'] / df['quantity'])

#Verify how many missing prices per unit remain
df['price_per_unit'].isnull().sum()

#check quantity. Let's see how many rows have a missing quantity
#where both total_spent and price_per_unit are available

df[df['quantity'].isnull() & df['price_per_unit'].notnull() & df['total_spent'].notnull()].shape[0]

#whenever quantity is missing,
#total_spent is also missing in those exact same rows

df[df['quantity'].isnull() & df['total_spent'].isnull() & df['item'].isnull()].shape[0]

#so if price unit is preset , 604 values of item, quantity and total spent are missing

"""see how many rows have a missing item where we do have quantity and total_spent"""

df[df['item'].isnull() & df['quantity'].notnull() & df['total_spent'].notnull()].shape[0]

#609 values of item is missing but quantity ad total spent are present.
#intotal 1213 values of item is missing

df['item'].isnull().sum()

# Check if category and price together point to a single unique item
df.groupby(['category', 'price_per_unit'])['item'].nunique().max()

#df['price_per_unit'].count()

# Group by category and price_per_unit, then get the first valid item name for each group
df['item'] = df['item'].fillna(df.groupby(['category', 'price_per_unit']) ['item'].transform('first'))

# Check how many missing items are left
df['item'].isnull().sum()

df.isnull().sum()

df[df['quantity'].isnull() & df['total_spent'].isnull() & df['price_per_unit'].notnull()].shape[0]

#we have 604 values where item , quantity and total spent missing,
#we filled item by using category and price per unit values
#now 604 quantity and total speent missing, but we have category
#item, and price per unit

# Find customer IDs that have missing quantities
missing_customers = df[df['quantity'].isnull()]['customer_id']

# 1. Recalculate total_spent for complete rows (leaves 604 rows as NaN)
df['total_spent'] = df['price_per_unit'] * df['quantity']

# 2. Add an indicator column flagging missing quantities (1 = missing, 0 = complete)
df['is_missing_quantity'] = df['quantity'].isnull().astype(int)

# 3. Create DataFrame 1 (All 12,575 rows with the flag column included)
df_with_missing = df.copy()

# 4. Create DataFrame 2 (11,971 complete rows, dropping missing quantities)
df_clean = df.dropna(subset=['quantity']).drop(columns=['is_missing_quantity']).copy()

# 5. Verify shapes and missing counts
print("df_with_missing shape:", df_with_missing.shape)

print("df_with_missing flagged rows:", df_with_missing['is_missing_quantity'].sum())

print("df_clean shape:", df_clean.shape)

print("df_clean missing quantities:", df_clean['quantity'].isnull().sum())

# Convert transaction_date to datetime format in both dataframes
df_with_missing['transaction_date'] = pd.to_datetime(df_with_missing['transaction_date'])
df_clean['transaction_date'] = pd.to_datetime(df_clean['transaction_date'])

from google.colab import files

# Save both DataFrames to CSV files
df_with_missing.to_csv('ecommerce_data_with_missing.csv', index=False)
df_clean.to_csv('ecommerce_data_clean.csv', index=False)

# Trigger direct browser downloads
files.download('ecommerce_data_with_missing.csv')
files.download('ecommerce_data_clean.csv')